config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :type, :pokemon, :trainer, :move, only: %i[index show] do
    collection do
      get 'search_results'
    end
  end
  get '/about', to: 'about#index'
  root to: 'pokemon#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/move.rb
# frozen_string_literal: true

class Move < ApplicationRecord
  validates :move, :accuracy, :power, :pp, presence: true
  validates :move, uniqueness: true
  belongs_to :type
  has_many :pokemon_moves
  has_many :pokemon, through: :pokemon_moves
end

app/models/pokemon.rb
# frozen_string_literal: true

class Pokemon < ApplicationRecord
  validates :name, :hp, :attack, :defence, :speed, :spAttack, :spDefense, presence: true
  validates :name, uniqueness: true

  has_many :pokemon_types
  has_many :pokemon_moves
  has_many :type, through: :pokemon_types
  has_many :move, through: :pokemon_moves
  has_many :trainer, through: :trainer_pokemon
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/trainer.rb
# frozen_string_literal: true

class Trainer < ApplicationRecord
  validates :name, :age, presence: true
  has_many :pokemon, through: :trainer_pokemon
end

app/models/trainer_pokemon.rb
class TrainerPokemon < ApplicationRecord
  belongs_to :trainer
  belongs_to :pokemon
end

app/models/type.rb
# frozen_string_literal: true

class Type < ApplicationRecord
  validates :pokemonType, presence: true, uniqueness: true

  has_many :pokemon_types
  has_many :pokemon, through: :pokemon_types
  # has_many :pokemon_moves
  # has_many :move, through: :pokemon_moves
  has_many :moves
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/move_controller.rb
# frozen_string_literal: true

class MoveController < ApplicationController
  def index
    all = Move.order(:move)
    @pagy, @move = pagy(all, items: 10)
  end

  def show
    @move = Move.find(params[:id])
    all = @move.pokemon
    @pagy, @pokemonWithMove = pagy(all, items: 10)
  end

  # GET /move/search_results
  def search_results
    @query = params[:query]
    all = Move.where('move LIKE ?', "%#{@query}%")
    @moveCount = all.count
    @pagy, @move = pagy(all, items: 10)
  end
end

app/controllers/pokemon_controller.rb
# frozen_string_literal: true

class PokemonController < ApplicationController
  include Pagy::Backend
  def index
    all = Pokemon.order(:name)
    @pagy, @pokemon = pagy(all, items: 10)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  # GET /pokemon/search_results
  def search_results
    @query = params[:query]
    all = Pokemon.where('name LIKE ?', "%#{@query}%")
    @pokemonCount = all.count
    @pagy, @pokemon = pagy(all, items: 10)
  end
end

app/controllers/pokemon_types_controller.rb
class PokemonTypesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/trainer_controller.rb
class TrainerController < ApplicationController
  def index
    all = Trainer.order(:name)
    @pagy, @trainer = pagy(all, items: 10)
  end

  def show
    @trainer = Trainer.find(params[:id])
  end

  # GET /trainer/search_results
  def search_results
    @query = params[:query]
    all = Trainer.where('name LIKE ?', "%#{@query}%")
    @trainerCount = all.count
    @pagy, @trainer = pagy(all, items: 10)
  end
end

app/controllers/type_controller.rb
# frozen_string_literal: true

class TypeController < ApplicationController
  def index
    all = Type.order(:pokemonType)
    @pagy, @type = pagy(all, items: 10)
  end

  def show
    @type = Type.find(params[:id])
    allPokemon = @type.pokemon
    @pagyPokemon, @pokemon = pagy(allPokemon, items: 10)
    allMoves = @type.moves
    @pagyMove, @move = pagy(allMoves, items: 10)
  end

  # GET /type/search_results
  def search_results
    @query = params[:query]
    all = Type.where('pokemonType LIKE ?', "%#{@query}%")
    @typeCount = all.count
    @pagy, @type = pagy(all, items: 10)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/move_helper.rb
module MoveHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/helpers/type_helper.rb
module TypeHelper
end

app/views/about/index.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
</nav>

<div style="width:500px;padding-left:50px;padding-top:20px;">
  <h1>About</h1>
  <p>Pokemon Frenzy gives you detailed information on all the worlds Pokemon and their moves.
  It also follows the worlds top trainers and their Pokemon. All Pokemon data comes from <a href="https://github.com/fanzeyi/pokemon.json">here</a> and
  all Pokemon Trainer data is randomly generated from <a href="https://github.com/faker-ruby/faker">Faker</a>.</p>
</div>

app/views/move/index.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_move_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search moves") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:640px">Pokemon Moves</h1>

<div class="container" style="margin:auto;">
  <% @move.each do |mo|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to mo.move, mo%></h4>
      <p class="card-text">HP: <%= mo.accuracy%></p>
      <p class="card-text">Attack: <%= mo.power%></p>
      <p class="card-text">Defense: <%= mo.pp%></p>
      <p class="card-text">Type: <%=link_to mo.type.pokemonType, mo.type%></p>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/move/search_results.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_move_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search moves") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:auto">Pokemon moves search results for "<%=@query%>"</h1>
<h3>Results: <%=@moveCount%></h3>

<div class="container" style="margin:auto;">
  <% @move.each do |mo|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to mo.move, mo%></h4>
      <p class="card-text">HP: <%= mo.accuracy%></p>
      <p class="card-text">Attack: <%= mo.power%></p>
      <p class="card-text">Defense: <%= mo.pp%></p>
      <p class="card-text">Type: <%=link_to mo.type.pokemonType, mo.type%></p>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/move/show.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
</nav>

<div class="card" style="width: 20rem;margin:0 auto;margin-top:10px;">
  <div class="card-body">
    <h3 class="card-title"><%= @move.move%></h3>
      <p class="card-text">HP: <%= @move.accuracy%></p>
      <p class="card-text">Attack: <%= @move.power%></p>
      <p class="card-text">Defense: <%= @move.pp%></p>
      <p class="card-text">Type: <%=link_to @move.type.pokemonType, @move.type%></p>
  </div>
</div>

<h3 style="margin-left:550px;margin-top:10px;">Pokemon that use <%= @move.move%></h3>

<div class="container" style="margin: 0 auto;">
  <% @pokemonWithMove.each do |poke|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to poke.name, poke%></h4>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/pokemon/index.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_pokemon_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search pokemon") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:640px">Pokemon</h1>

<div class="container" style="margin: 0 auto;">
  <% @pokemon.each do |poke|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to poke.name, poke%></h4>
      <p class="card-text">HP: <%= poke.hp%></p>
      <p class="card-text">Attack: <%= poke.attack%></p>
      <p class="card-text">Defense: <%= poke.defence%></p>
      <p class="card-text">Speed: <%= poke.speed%></p>
      <p class="card-text">SpAttack <%= poke.spAttack%></p>
      <p class="card-text">SpDefense <%= poke.spDefense%></p>
      <p class="card-text"><%=if poke.type.count > 1
          'Types: '
        else
          'Type: '
        end %>
        <% poke.type.each do |ty|%>
        <%=link_to ty.pokemonType, ty%>
        <% end %>
      </p>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/pokemon/search_results.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_pokemon_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search pokemon") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:auto">Pokemon Search results for "<%=@query%>"</h1>
<h3>Results: <%=@pokemonCount%></h3>

<div class="container" style="margin:auto;">
  <% @pokemon.each do |poke|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to poke.name, poke%></h4>
      <p class="card-text">HP: <%= poke.hp%></p>
      <p class="card-text">Attack: <%= poke.attack%></p>
      <p class="card-text">Defense: <%= poke.defence%></p>
      <p class="card-text">Speed: <%= poke.speed%></p>
      <p class="card-text">SpAttack <%= poke.spAttack%></p>
      <p class="card-text">SpDefense <%= poke.spDefense%></p>
      <p class="card-text"><%=if poke.type.count > 1
          'Types: '
        else
          'Type: '
        end %>
        <% poke.type.each do |ty|%>
        <%=link_to ty.pokemonType, ty%>
        <% end %>
      </p>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/pokemon/show.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
</nav>

<div class="card" style="width: 20rem;margin:0 auto;margin-top:10px;">
  <div class="card-body">
    <h3 class="card-title"><%= @pokemon.name%></h3>
      <p class="card-text">HP: <%= @pokemon.hp%></p>
      <p class="card-text">Attack: <%= @pokemon.attack%></p>
      <p class="card-text">Defense: <%= @pokemon.defence%></p>
      <p class="card-text">Speed: <%= @pokemon.speed%></p>
      <p class="card-text">SpAttack <%= @pokemon.spAttack%></p>
      <p class="card-text">SpDefense <%= @pokemon.spDefense%></p>
      <p class="card-text"><%=if @pokemon.type.count > 1
          'Types: '
        else
          'Type: '
        end %>
        <% @pokemon.type.each do |ty|%>
        <%=link_to ty.pokemonType, ty%>
        <% end %>
      </p>
  </div>
  <div class="card-body">
    <h5 class="card-title">Moves</h5>
    <% @pokemon.move.each do |mv| %>
      <p class="card-text"><%=link_to mv.move, mv%></p>
    <% end %>
  </div>
</div>

app/views/pokemon_types/index.html.erb
<h1>PokemonTypes#index</h1>
<p>Find me in app/views/pokemon_types/index.html.erb</p>

app/views/pokemon_types/show.html.erb
<h1>PokemonTypes#show</h1>
<p>Find me in app/views/pokemon_types/show.html.erb</p>

app/views/trainer/index.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_trainer_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search trainers") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:640px">Trainer</h1>

<div class="container" style="margin:auto;">
  <% @trainer.each do |train|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to train.name, train%></h4>
      <p class="card-text">Age: <%= train.age%></p>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/trainer/search_results.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_trainer_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search trainers") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:auto">Trainer Search results for "<%=@query%>"</h1>
<h3>Results: <%=@trainerCount%></h3>

<div class="container" style="margin:auto;">
  <% @trainer.each do |train|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to train.name, train%></h4>
      <p class="card-text">Age: <%= train.age%></p>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/trainer/show.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
</nav>

<div class="card" style="width: 20rem;margin:0 auto;margin-top:10px;">
  <div class="card-body">
    <div class="card-body">
      <h4 class="card-title"><%=@trainer.name%></h4>
      <p class="card-text">Age: <%= @trainer.age%></p>
    </div>
  </div>
</div>

app/views/type/index.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_type_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search pokemon types") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:640px">Pokemon Type</h1>

<div class="container" style="margin:auto;">
  <% @type.each do |ty|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to ty.pokemonType, ty%></h4>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/type/search_results.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
    <%= form_with(url: search_results_type_index_path, method: "get",class:"form-inline", local: true) do %>
      <%= text_field_tag(:query,"",class:"form-control mr-sm-2", placeholder:"Search pokemon types") %>
      <%= submit_tag("Search",class:"btn btn-success " ) %>
    <% end %>
</nav>

<h1 style="margin-left:auto">Pokemon Type search results for "<%=@query%>"</h1>
<h3>Results: <%=@typeCount%></h3>

<div class="container" style="margin:auto;">
  <% @type.each do |ty|%>
  <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
    <div class="card-body">
      <h4 class="card-title"><%=link_to ty.pokemonType, ty%></h4>
    </div>
  </div>
  <% end %>
  <%==pagy_nav(@pagy)%>
</div>

app/views/type/show.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item"><a class="nav-link" href="/pokemon">Pokedex</a></li>
      <li class="nav-item"><a class="nav-link" href="/move">Moves</a></li>
      <li class="nav-item"><a class="nav-link" href="/type">Types</a></li>
      <li class="nav-item"><a class="nav-link" href="/trainer">Trainers</a></li>
      <li class="nav-item"><a class="nav-link" href="/about">About</a></li>
    </ul>
</nav>

<h1 style="margin:0px auto;width:10%;"><%= @type.pokemonType %></h1>

<div style="margin-top: 50px;">
  <h3 style="margin-left:600px;">Pokemon of type <%= @type.pokemonType %></h3>
  <div class="container" style="margin: 0 auto;">
    <% @pokemon.each do |poke|%>
    <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to poke.name, poke%></h4>
        <p class="card-text">HP: <%= poke.hp%></p>
        <p class="card-text">Attack: <%= poke.attack%></p>
        <p class="card-text">Defense: <%= poke.defence%></p>
        <p class="card-text">Speed: <%= poke.speed%></p>
        <p class="card-text">SpAttack <%= poke.spAttack%></p>
        <p class="card-text">SpDefense <%= poke.spDefense%></p>
        <p class="card-text"><%=if poke.type.count > 1
            'Types: '
          else
            'Type: '
          end %>
          <% poke.type.each do |ty|%>
          <%=link_to ty.pokemonType, ty%>
          <% end %>
        </p>
      </div>
    </div>
    <% end %>
    <%==pagy_nav(@pagyPokemon)%>
  </div>
</div>

<div style="float:left;margin-left: 190px;margin-top: 20px;">
  <h3 style="margin-left:425px;">Moves of type <%= @type.pokemonType %></h3>
  <div class="container">
    <% @move.each do |mo|%>
    <div class="card bg-dark text-white" style="margin-bottom:10px;margin-left:10px;width:500px;float:left;">
      <div class="card-body">
        <h4 class="card-title"><%=link_to mo.move, mo%></h4>
        <p class="card-text">HP: <%= mo.accuracy%></p>
        <p class="card-text">Attack: <%= mo.power%></p>
        <p class="card-text">Defense: <%= mo.pp%></p>
        <p class="card-text">Type: <%=link_to mo.type.pokemonType, mo.type%></p>
      </div>
    </div>
    <% end %>
    <%==pagy_nav(@pagyMove)%>
  </div>
</div>